/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddInquiryArgs {
  'customerName' : string,
  'customerPhone' : string,
  'guestCount' : bigint,
  'message' : string,
  'customerEmail' : string,
  'packageId' : string,
  'eventDate' : string,
  'eventType' : string,
}
export interface Inquiry {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'guestCount' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'customerEmail' : string,
  'packageId' : string,
  'eventDate' : string,
  'eventType' : string,
}
export interface Package {
  'id' : string,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addInquiry' : ActorMethod<[AddInquiryArgs], bigint>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getInquiry' : ActorMethod<[bigint], [] | [Inquiry]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];